import Head from 'next/head';
import React, { lazy, memo } from 'react'
import { UiStaticData } from '../api/customCms/db/utils.interface';


const Inventory = lazy(() => import('@/components/mains/dashboard/utils/inventory/Inventory'));

export default memo(function EditProduct({ CMS }: UiStaticData) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {
                CMS && (<Inventory ui_inventory={CMS.dashboard.portal.components.inventory} />)
            }
        </>
    )
})

export const getServerSideProps = async () => {
    try {
        const response = await fetch(`${process.env.VERCEL_URL_CORS}/api/customCms`);
        const CMS = await response.json();
        return {
            props: {
                CMS,
            },
        };
    } catch (error) {
        console.error('Error in getServerSideProps:', error);
        return {
            props: {
                error: 'An error occurred while fetching server-side data.',
            },
        };
    }
};