import { memo } from 'react';
import Head from 'next/head';
import { UiStaticData } from './api/customCms/db/utils.interface';
import CreateProduct from '@/components/mains/dashboard/create-product/CreateProduct';

export default memo(function Products({ CMS }: UiStaticData) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {
                CMS.create_products && (<CreateProduct create_products={CMS.create_products} />)
            }
        </>
    )
})

export const getServerSideProps = async () => {
    try {
        const response = await fetch(`${process.env.VERCEL_URL_CORS}/api/customCms`);
        const CMS = await response.json();
        return {
            props: {
                CMS,
            },
        };
    } catch (error) {
        console.error('Error in getServerSideProps:', error);
        return {
            props: {
                error: 'An error occurred while fetching server-side data.',
            },
        };
    }
};